name: "Local Sound Output Add-On"
description: "Play sounds and make acoustic notifications using the audio output (audio jack) of your Home Assistant server, e.g. Raspberry Pi. This is not intended to be a media player, but for use of sounds in automations, scripts and so on."
version: "0.0.1"
slug: "local_sound_output"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386